### ISSUE TITLE
3x get comment requests sent to API when opening and closing an expression in the collective

### ISSUE THREAD

**Issue by jdeepee** [juntofoundation/junto-mobile#1003]
One request gets made when I click the expression. And then another two when I close it. Lets try to remove these two to reduce API load.

**Comment by jdeepee** [comment]
Note this seems to only happen when using an iOS gesture to go back and now when using the back button explicitly

**Comment by sunyatax** [comment]
@fayeed can you take a look?

**Comment by fayeed** [comment]
@sunyatax This happens because of the swipe to go back the reason is once you start swiping it updates some internal property which triggers the `didChangeDependencies` method which then makes the call to get the comments and once it ends it call it again, so we get two calls from here. 

We could move the call from `didChangeDependencies` to `initState` but then it won't update the comments if you add comments in it.

**Comment by sunyatax** [comment]
Where are we at on this?

**Comment by fayeed** [comment]
I was not able to find a way to fix this, maybe @Nash0x7E2 can take a quick look.

**Comment by sunyatax** [comment]
@Nash0x7E2 let us know, thanks

**Comment by jdeepee** [comment]
Any news on this one? @sunyatax @Nash0x7E2
