### ISSUE TITLE
After posting in community center feedback user should be shown feedback tab, not updates

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1133]

**Comment by fayeed** [comment]
@sunyatax whenever I go to the center screen, I kept getting 404 from the API, I am on `v0.2.3-alpha`.

**Comment by sunyatax** [comment]
Ah, this is probably because we keep wiping the dev database and need to recreate a community center group. Let me take care of that...

**Comment by sunyatax** [comment]
Okay, you should be good now @fayeed

**Comment by fayeed** [comment]
@sunyatax I think the DB got wiped again, not being able to create the feedback again.

**Comment by fayeed** [comment]
@sunyatax The reason we are getting moved back to updates is that because we are using `pushAndRemoveUntil` so it pushes a new route and removes all the routes, we can use `popUntil` but there are two issues with it, first there is weird animation issue with it there is already an issue opened on Flutter repo, second we will need to use named routes, and we are not using any right now.
