### ISSUE TITLE
Navigation for nested comments

### ISSUE THREAD

**Issue by sunyatax** [juntofoundation/junto-mobile#1150]
Clicking on the CommentParent should navigate/push to an ExpressionOpen of that content

**Comment by fayeed** [comment]
@sunyatax If I tap on a second item in the thread should it retain the parent above it when it moves to the next page or not? I tried using the API to implement this behavior it was returning all the wrong items, let's say I have 4 expressions long thread I tap on the topmost expression, the expected behavior would be for it to return no parents right, but I still get all the parents while keeping the current expression as the source expression. Seems like the backend is returning all the related expressions in the `comment_thread` property.

**Comment by fayeed** [comment]
For now, I have just made it so it navigates to the tapped expression, no parents attached. Let me know if the above comment is the expected behavior, but that will require backend changes.

**Comment by fayeed** [comment]
@sunyatax If you want to test the current behavior you can try the `comment-navigation-thread` branch.

**Comment by sunyatax** [comment]
Hey @fayeed -- 

Yep, the expected behavior is that if I'm on a comment where there are 4 parents, and I press the 4th one down, it should open a CommentOpen with 3 parents above it. If the API is not returning the correct data, please ping Josh.
