### ISSUE TITLE
Duplicate Lotus navigation bar 

### ISSUE THREAD

**Issue by Nash0x7E2** [juntofoundation/junto-mobile#737]
Steps to reproduce:
1. Navigate to collective screen 
2. Swipe to expose the drawer

**Comment by sunyatax** [comment]
Thanks for taking care of this Nash. The issue is bc we’re using a PageView in the collective now. When you fix this, please make sure the lotus is still available in both the expression feed and perspectives list. And could you also touch up the lotus in the Packs section too? When you press on someone’s pack you’ll see what I’m talking about.

**Comment by Nash0x7E2** [comment]
Ok cool, working on this today so I’ll have a look 👍🏻
